// <auto-generated />
using System;
using EcoShrimp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EcoShrimp.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250411090054_add-tble-AppPolicies")]
    partial class addtbleAppPolicies
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("EcoShrimp.Data.Entities.AppCateNews", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Desc")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("app_cateNew", (string)null);
                });

            modelBuilder.Entity("EcoShrimp.Data.Entities.AppCategories", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Desc")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("app_categories", (string)null);
                });

            modelBuilder.Entity("EcoShrimp.Data.Entities.AppConnects", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Desc")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("IdProInstances")
                        .HasColumnType("int");

                    b.Property<int>("IdSeason")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("IdProInstances");

                    b.HasIndex("IdSeason");

                    b.ToTable("app_connects", (string)null);
                });

            modelBuilder.Entity("EcoShrimp.Data.Entities.AppDataSensor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<double?>("DO")
                        .HasColumnType("double");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("IdConnect")
                        .HasColumnType("int");

                    b.Property<double?>("Nh4")
                        .HasColumnType("double");

                    b.Property<double?>("PH")
                        .HasColumnType("double");

                    b.Property<double?>("Sal")
                        .HasColumnType("double");

                    b.Property<double?>("Tds")
                        .HasColumnType("double");

                    b.Property<double?>("Temp")
                        .HasColumnType("double");

                    b.Property<double?>("Tur")
                        .HasColumnType("double");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("IdConnect");

                    b.ToTable("app_data_sensor", (string)null);
                });

            modelBuilder.Entity("EcoShrimp.Data.Entities.AppFarms", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Avatar")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("City")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Desc")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<string>("District")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("Email")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("FarmName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<int?>("IdTime")
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<string>("NumberHouse")
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<string>("OwnerName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PassWord")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Ward")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.HasKey("Id");

                    b.ToTable("app_farms", (string)null);
                });

            modelBuilder.Entity("EcoShrimp.Data.Entities.AppImges", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("IdProduct")
                        .HasColumnType("int");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("IdProduct");

                    b.ToTable("app_imges", (string)null);
                });

            modelBuilder.Entity("EcoShrimp.Data.Entities.AppNews", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("IdCateNew")
                        .HasColumnType("int");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("varchar(2048)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("varchar(1024)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("IdCateNew");

                    b.ToTable("app_news", (string)null);
                });

            modelBuilder.Entity("EcoShrimp.Data.Entities.AppPermissions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Desc")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("Table")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("app_permissions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 8102,
                            Code = "CREATE",
                            CreatedDate = new DateTime(2024, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Desc = "Thêm người dùng",
                            GroupName = "Quản lý người dùng",
                            Table = "AppUsers"
                        },
                        new
                        {
                            Id = 8101,
                            Code = "VIEW_LIST",
                            CreatedDate = new DateTime(2024, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Desc = "Xem danh sách người dùng",
                            GroupName = "Quản lý người dùng",
                            Table = "AppUsers"
                        },
                        new
                        {
                            Id = 8103,
                            Code = "UPDATE",
                            CreatedDate = new DateTime(2024, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Desc = "Cập nhật người dùng",
                            GroupName = "Quản lý người dùng",
                            Table = "AppUsers"
                        },
                        new
                        {
                            Id = 8104,
                            Code = "DELETE",
                            CreatedDate = new DateTime(2024, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Desc = "Xóa người dùng",
                            GroupName = "Quản lý người dùng",
                            Table = "AppUsers"
                        },
                        new
                        {
                            Id = 1102,
                            Code = "CREATE",
                            CreatedDate = new DateTime(2024, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Desc = "Thêm danh mục",
                            GroupName = "Quản lý danh mục",
                            Table = "AppCategories"
                        },
                        new
                        {
                            Id = 1101,
                            Code = "VIEW_LIST",
                            CreatedDate = new DateTime(2024, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Desc = "Xem danh sách danh mục",
                            GroupName = "Quản lý danh mục",
                            Table = "AppCategories"
                        },
                        new
                        {
                            Id = 1103,
                            Code = "UPDATE",
                            CreatedDate = new DateTime(2024, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Desc = "Cập nhật danh mục",
                            GroupName = "Quản lý danh mục",
                            Table = "AppCategories"
                        },
                        new
                        {
                            Id = 1104,
                            Code = "DELETE",
                            CreatedDate = new DateTime(2024, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Desc = "Xóa danh mục",
                            GroupName = "Quản lý danh mục",
                            Table = "AppCategories"
                        },
                        new
                        {
                            Id = 1105,
                            Code = "VIEW_DETAIL",
                            CreatedDate = new DateTime(2024, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Desc = "Xem chi tiết danh mục",
                            GroupName = "Quản lý danh mục",
                            Table = "AppCategories"
                        },
                        new
                        {
                            Id = 2102,
                            Code = "CREATE",
                            CreatedDate = new DateTime(2024, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Desc = "Thêm danh mục tin tức",
                            GroupName = "Quản lý danh mục tin tức",
                            Table = "AppCateNews"
                        },
                        new
                        {
                            Id = 2101,
                            Code = "VIEW_LIST",
                            CreatedDate = new DateTime(2024, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Desc = "Xem danh sách danh mục tin tức",
                            GroupName = "Quản lý danh mục tin tức",
                            Table = "AppCateNews"
                        },
                        new
                        {
                            Id = 2103,
                            Code = "UPDATE",
                            CreatedDate = new DateTime(2024, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Desc = "Cập nhật danh mục tin tức",
                            GroupName = "Quản lý danh mục tin tức",
                            Table = "AppCateNews"
                        },
                        new
                        {
                            Id = 2104,
                            Code = "DELETE",
                            CreatedDate = new DateTime(2024, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Desc = "Xóa danh mục tin tức",
                            GroupName = "Quản lý danh mục tin tức",
                            Table = "AppCateNews"
                        },
                        new
                        {
                            Id = 2105,
                            Code = "VIEW_DETAIL",
                            CreatedDate = new DateTime(2024, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Desc = "Xem chi tiết danh mục tin tức",
                            GroupName = "Quản lý danh mục tin tức",
                            Table = "AppCateNews"
                        },
                        new
                        {
                            Id = 3102,
                            Code = "CREATE",
                            CreatedDate = new DateTime(2024, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Desc = "Thêm trang trại",
                            GroupName = "Quản lý trang trại",
                            Table = "AppFarms"
                        },
                        new
                        {
                            Id = 3101,
                            Code = "VIEW_LIST",
                            CreatedDate = new DateTime(2024, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Desc = "Xem danh sách trang trại",
                            GroupName = "Quản lý trang trại",
                            Table = "AppFarms"
                        },
                        new
                        {
                            Id = 3103,
                            Code = "UPDATE",
                            CreatedDate = new DateTime(2024, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Desc = "Cập nhật trang trại",
                            GroupName = "Quản lý trang trại",
                            Table = "AppFarms"
                        },
                        new
                        {
                            Id = 3104,
                            Code = "DELETE",
                            CreatedDate = new DateTime(2024, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Desc = "Xóa trang trại",
                            GroupName = "Quản lý trang trại",
                            Table = "AppFarms"
                        },
                        new
                        {
                            Id = 3105,
                            Code = "VIEW_DETAIL",
                            CreatedDate = new DateTime(2024, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Desc = "Xem chi tiết trang trại",
                            GroupName = "Quản lý trang trại",
                            Table = "AppFarms"
                        },
                        new
                        {
                            Id = 4102,
                            Code = "CREATE",
                            CreatedDate = new DateTime(2024, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Desc = "Thêm tin tức",
                            GroupName = "Quản lý tin tức",
                            Table = "AppNews"
                        },
                        new
                        {
                            Id = 4101,
                            Code = "VIEW_LIST",
                            CreatedDate = new DateTime(2024, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Desc = "Xem danh sách tin tức",
                            GroupName = "Quản lý tin tức",
                            Table = "AppNews"
                        },
                        new
                        {
                            Id = 4103,
                            Code = "UPDATE",
                            CreatedDate = new DateTime(2024, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Desc = "Cập nhật tin tức",
                            GroupName = "Quản lý tin tức",
                            Table = "AppNews"
                        },
                        new
                        {
                            Id = 4104,
                            Code = "DELETE",
                            CreatedDate = new DateTime(2024, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Desc = "Xóa tin tức",
                            GroupName = "Quản lý tin tức",
                            Table = "AppNews"
                        },
                        new
                        {
                            Id = 4105,
                            Code = "VIEW_DETAIL",
                            CreatedDate = new DateTime(2024, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Desc = "Xem chi tiết tin tức",
                            GroupName = "Quản lý tin tức",
                            Table = "AppNews"
                        },
                        new
                        {
                            Id = 5102,
                            Code = "CREATE",
                            CreatedDate = new DateTime(2024, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Desc = "Thêm sản phẩm",
                            GroupName = "Quản lý sản phẩm",
                            Table = "AppProducts"
                        },
                        new
                        {
                            Id = 5101,
                            Code = "VIEW_LIST",
                            CreatedDate = new DateTime(2024, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Desc = "Xem danh sách sản phẩm",
                            GroupName = "Quản lý sản phẩm",
                            Table = "AppProducts"
                        },
                        new
                        {
                            Id = 5103,
                            Code = "UPDATE",
                            CreatedDate = new DateTime(2024, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Desc = "Cập nhật sản phẩm",
                            GroupName = "Quản lý sản phẩm",
                            Table = "AppProducts"
                        },
                        new
                        {
                            Id = 5104,
                            Code = "DELETE",
                            CreatedDate = new DateTime(2024, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Desc = "Xóa sản phẩm",
                            GroupName = "Quản lý sản phẩm",
                            Table = "AppProducts"
                        },
                        new
                        {
                            Id = 5105,
                            Code = "VIEW_DETAIL",
                            CreatedDate = new DateTime(2024, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Desc = "Xem chi tiết sản phẩm",
                            GroupName = "Quản lý sản phẩm",
                            Table = "AppProducts"
                        },
                        new
                        {
                            Id = 6102,
                            Code = "CREATE",
                            CreatedDate = new DateTime(2024, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Desc = "Thêm yêu cầu",
                            GroupName = "Quản lý yêu cầu",
                            Table = "AppRequests"
                        },
                        new
                        {
                            Id = 6101,
                            Code = "VIEW_LIST",
                            CreatedDate = new DateTime(2024, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Desc = "Xem danh sách yêu cầu",
                            GroupName = "Quản lý yêu cầu",
                            Table = "AppRequests"
                        },
                        new
                        {
                            Id = 6103,
                            Code = "UPDATE",
                            CreatedDate = new DateTime(2024, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Desc = "Cập nhật yêu cầu",
                            GroupName = "Quản lý yêu cầu",
                            Table = "AppRequests"
                        },
                        new
                        {
                            Id = 6104,
                            Code = "DELETE",
                            CreatedDate = new DateTime(2024, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Desc = "Xóa yêu cầu",
                            GroupName = "Quản lý yêu cầu",
                            Table = "AppRequests"
                        },
                        new
                        {
                            Id = 6105,
                            Code = "VIEW_DETAIL",
                            CreatedDate = new DateTime(2024, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Desc = "Xem chi tiết yêu cầu",
                            GroupName = "Quản lý yêu cầu",
                            Table = "AppRequests"
                        },
                        new
                        {
                            Id = 7102,
                            Code = "CREATE",
                            CreatedDate = new DateTime(2024, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Desc = "Thêm vai trò",
                            GroupName = "Quản lý vai trò",
                            Table = "AppRoles"
                        },
                        new
                        {
                            Id = 7101,
                            Code = "VIEW_LIST",
                            CreatedDate = new DateTime(2024, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Desc = "Xem danh sách vai trò",
                            GroupName = "Quản lý vai trò",
                            Table = "AppRoles"
                        },
                        new
                        {
                            Id = 7103,
                            Code = "UPDATE",
                            CreatedDate = new DateTime(2024, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Desc = "Cập nhật vai trò",
                            GroupName = "Quản lý vai trò",
                            Table = "AppRoles"
                        },
                        new
                        {
                            Id = 7104,
                            Code = "DELETE",
                            CreatedDate = new DateTime(2024, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Desc = "Xóa vai trò",
                            GroupName = "Quản lý vai trò",
                            Table = "AppRoles"
                        },
                        new
                        {
                            Id = 7105,
                            Code = "VIEW_DETAIL",
                            CreatedDate = new DateTime(2024, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Desc = "Xem chi tiết vai trò",
                            GroupName = "Quản lý vai trò",
                            Table = "AppRoles"
                        });
                });

            modelBuilder.Entity("EcoShrimp.Data.Entities.AppPolicies", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(262144)
                        .HasColumnType("longtext");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("varchar(1024)");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("varchar(1024)");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("app_policies", (string)null);
                });

            modelBuilder.Entity("EcoShrimp.Data.Entities.AppPonds", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<decimal?>("Area")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Desc")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<int>("IdFarm")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("IdFarm");

                    b.ToTable("app_ponds", (string)null);
                });

            modelBuilder.Entity("EcoShrimp.Data.Entities.AppProInstances", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("BuyDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Desc")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<string>("IP")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<int?>("IdFarm")
                        .HasColumnType("int");

                    b.Property<int>("IdProduct")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<int?>("Port")
                        .HasColumnType("int");

                    b.Property<string>("SeriNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("IdFarm");

                    b.HasIndex("IdProduct");

                    b.ToTable("app_product_Instances", (string)null);
                });

            modelBuilder.Entity("EcoShrimp.Data.Entities.AppProducts", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Desc")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("IdCategory")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<double>("OriginalPrice")
                        .HasColumnType("double");

                    b.Property<double>("SalePrice")
                        .HasColumnType("double");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<int>("TotalQuantity")
                        .HasColumnType("int");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Video")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.HasKey("Id");

                    b.HasIndex("IdCategory");

                    b.ToTable("app_products", (string)null);
                });

            modelBuilder.Entity("EcoShrimp.Data.Entities.AppRequests", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("varchar(4096)");

                    b.Property<string>("ContentFeedback")
                        .HasMaxLength(4096)
                        .HasColumnType("varchar(4096)");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(96)
                        .HasColumnType("varchar(96)");

                    b.Property<DateTime?>("FeedbackDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Phone")
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TitleFeedback")
                        .HasMaxLength(1024)
                        .HasColumnType("varchar(1024)");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("app_requests", (string)null);
                });

            modelBuilder.Entity("EcoShrimp.Data.Entities.AppRolePermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("IdPermission")
                        .HasColumnType("int");

                    b.Property<int>("IdRole")
                        .HasColumnType("int");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("IdPermission");

                    b.HasIndex("IdRole");

                    b.ToTable("app_role_per", (string)null);
                });

            modelBuilder.Entity("EcoShrimp.Data.Entities.AppRoles", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Desc")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<int?>("SortOrder")
                        .HasColumnType("int");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("app_roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2024, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Desc = "Quản trị toàn bộ hệ thống",
                            Name = "Quản trị hệ thống"
                        });
                });

            modelBuilder.Entity("EcoShrimp.Data.Entities.AppSeasons", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("Density")
                        .HasColumnType("int");

                    b.Property<string>("Desc")
                        .HasMaxLength(2048)
                        .HasColumnType("varchar(2048)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("IdPond")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("IdPond");

                    b.ToTable("app_seasons", (string)null);
                });

            modelBuilder.Entity("EcoShrimp.Data.Entities.AppShrimp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("FacebookUrl")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<string>("InstagramUrl")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<string>("Logan")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<string>("LogoUrl")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("varchar(1024)");

                    b.Property<string>("Map")
                        .HasMaxLength(1024)
                        .HasColumnType("varchar(1024)");

                    b.Property<string>("OpentTime")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<string>("SubPhone")
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<string>("TwitterUrl")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("WebsiteName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("YouTubeUrl")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.HasKey("Id");

                    b.ToTable("app_shrimp", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Hẻm 388, P An Khánh, Q Ninh Kiều, TPCT",
                            Email = "quocduyctvn@gmail.com",
                            FacebookUrl = "https://facebook.com/ecoshrimp",
                            InstagramUrl = "https://instagram.com/ecoshrimp",
                            Logan = "EcoShrimp, Công nghệ IoT – Đồng hành cùng người nuôi tôm trong kỷ nguyên số!",
                            LogoUrl = "/assets/images/logo/logo-EcoShrimp-text.png",
                            Map = "",
                            OpentTime = "T2 - T7: 7h30 đến 16h00",
                            Phone = "090 100 7221",
                            SubPhone = "034 888 6431",
                            TwitterUrl = "https://twitter.com/ecoshrimp",
                            WebsiteName = "EcoShrimp.com",
                            YouTubeUrl = "https://youtube.com/ecoshrimp"
                        });
                });

            modelBuilder.Entity("EcoShrimp.Data.Entities.AppTimeIntervals", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("app_time_intervel", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Label = "1 Phút",
                            Value = 1
                        },
                        new
                        {
                            Id = 2,
                            Label = "5 Phút",
                            Value = 5
                        },
                        new
                        {
                            Id = 3,
                            Label = "10 Phút",
                            Value = 10
                        },
                        new
                        {
                            Id = 4,
                            Label = "30 Phút",
                            Value = 30
                        },
                        new
                        {
                            Id = 5,
                            Label = "1 Tiếng",
                            Value = 60
                        });
                });

            modelBuilder.Entity("EcoShrimp.Data.Entities.AppUsers", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(256)
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<string>("Avatar")
                        .HasMaxLength(1024)
                        .HasColumnType("varchar(1024)");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<int>("IdRole")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Pass")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<int?>("SortOrder")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("IdRole");

                    b.ToTable("app_users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "132, Hưng Lợi, Ninh Kiều, Cần Thơ",
                            CreatedDate = new DateTime(2024, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "quocduyctvn@gmail.com",
                            IdRole = 1,
                            Name = "Quốc Duy",
                            Pass = "$2a$10$UztMrBTzbwcXw/c3NJiRyOl/AkHVbj/td.2hb.6FcfPTqCTB5Ooyy",
                            Phone = "0901007221",
                            Status = 1
                        });
                });

            modelBuilder.Entity("EcoShrimp.Data.Entities.AppConnects", b =>
                {
                    b.HasOne("EcoShrimp.Data.Entities.AppProInstances", "appProInstances")
                        .WithMany("appConnects")
                        .HasForeignKey("IdProInstances")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EcoShrimp.Data.Entities.AppSeasons", "appSeasons")
                        .WithMany("appConnects")
                        .HasForeignKey("IdSeason")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("appProInstances");

                    b.Navigation("appSeasons");
                });

            modelBuilder.Entity("EcoShrimp.Data.Entities.AppDataSensor", b =>
                {
                    b.HasOne("EcoShrimp.Data.Entities.AppConnects", "appConnect")
                        .WithMany("appDataSensors")
                        .HasForeignKey("IdConnect")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("appConnect");
                });

            modelBuilder.Entity("EcoShrimp.Data.Entities.AppImges", b =>
                {
                    b.HasOne("EcoShrimp.Data.Entities.AppProducts", "appProduct")
                        .WithMany("appImges")
                        .HasForeignKey("IdProduct")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("appProduct");
                });

            modelBuilder.Entity("EcoShrimp.Data.Entities.AppNews", b =>
                {
                    b.HasOne("EcoShrimp.Data.Entities.AppCateNews", "appCateNew")
                        .WithMany("appNews")
                        .HasForeignKey("IdCateNew")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("appCateNew");
                });

            modelBuilder.Entity("EcoShrimp.Data.Entities.AppPonds", b =>
                {
                    b.HasOne("EcoShrimp.Data.Entities.AppFarms", "appFarm")
                        .WithMany("appPonds")
                        .HasForeignKey("IdFarm")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("appFarm");
                });

            modelBuilder.Entity("EcoShrimp.Data.Entities.AppProInstances", b =>
                {
                    b.HasOne("EcoShrimp.Data.Entities.AppFarms", "appFarm")
                        .WithMany("appProInstances")
                        .HasForeignKey("IdFarm");

                    b.HasOne("EcoShrimp.Data.Entities.AppProducts", "appProducts")
                        .WithMany("appProInstances")
                        .HasForeignKey("IdProduct")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("appFarm");

                    b.Navigation("appProducts");
                });

            modelBuilder.Entity("EcoShrimp.Data.Entities.AppProducts", b =>
                {
                    b.HasOne("EcoShrimp.Data.Entities.AppCategories", "appCategory")
                        .WithMany("appProducts")
                        .HasForeignKey("IdCategory")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("appCategory");
                });

            modelBuilder.Entity("EcoShrimp.Data.Entities.AppRolePermission", b =>
                {
                    b.HasOne("EcoShrimp.Data.Entities.AppPermissions", "appPermission")
                        .WithMany("appRolePermissions")
                        .HasForeignKey("IdPermission")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EcoShrimp.Data.Entities.AppRoles", "appRole")
                        .WithMany("appRolePermissions")
                        .HasForeignKey("IdRole")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("appPermission");

                    b.Navigation("appRole");
                });

            modelBuilder.Entity("EcoShrimp.Data.Entities.AppSeasons", b =>
                {
                    b.HasOne("EcoShrimp.Data.Entities.AppPonds", "appPond")
                        .WithMany("appSeasons")
                        .HasForeignKey("IdPond")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("appPond");
                });

            modelBuilder.Entity("EcoShrimp.Data.Entities.AppUsers", b =>
                {
                    b.HasOne("EcoShrimp.Data.Entities.AppRoles", "appRole")
                        .WithMany("appUsers")
                        .HasForeignKey("IdRole")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("appRole");
                });

            modelBuilder.Entity("EcoShrimp.Data.Entities.AppCateNews", b =>
                {
                    b.Navigation("appNews");
                });

            modelBuilder.Entity("EcoShrimp.Data.Entities.AppCategories", b =>
                {
                    b.Navigation("appProducts");
                });

            modelBuilder.Entity("EcoShrimp.Data.Entities.AppConnects", b =>
                {
                    b.Navigation("appDataSensors");
                });

            modelBuilder.Entity("EcoShrimp.Data.Entities.AppFarms", b =>
                {
                    b.Navigation("appPonds");

                    b.Navigation("appProInstances");
                });

            modelBuilder.Entity("EcoShrimp.Data.Entities.AppPermissions", b =>
                {
                    b.Navigation("appRolePermissions");
                });

            modelBuilder.Entity("EcoShrimp.Data.Entities.AppPonds", b =>
                {
                    b.Navigation("appSeasons");
                });

            modelBuilder.Entity("EcoShrimp.Data.Entities.AppProInstances", b =>
                {
                    b.Navigation("appConnects");
                });

            modelBuilder.Entity("EcoShrimp.Data.Entities.AppProducts", b =>
                {
                    b.Navigation("appImges");

                    b.Navigation("appProInstances");
                });

            modelBuilder.Entity("EcoShrimp.Data.Entities.AppRoles", b =>
                {
                    b.Navigation("appRolePermissions");

                    b.Navigation("appUsers");
                });

            modelBuilder.Entity("EcoShrimp.Data.Entities.AppSeasons", b =>
                {
                    b.Navigation("appConnects");
                });
#pragma warning restore 612, 618
        }
    }
}
